[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Davi", email = "aaa@aaa"},
]
dependencies = [
    "django>=4.2",
]
requires-python = ">=3.10"
license = {text = "MIT"}
